name: club_cash
description: Simple and straightforward, focusing on the financial aspect of club.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  connectivity_plus: ^7.0.0
  extended_image: ^10.0.1
  http: ^1.6.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  shimmer: ^3.0.0
  flutter_svg: ^2.2.2
  url_launcher: ^6.3.2
  logger: ^2.6.1
  lottie: ^3.3.1
  dropdown_search: ^6.0.2
  get: ^4.7.2
  get_storage: ^2.1.1
  contacts_service:
    git: https://github.com/Flutter-Tent/flutter_contacts.git
  permission_handler: ^12.0.1
  pin_code_fields: ^8.0.1
  package_info_plus: ^8.3.1

#  # SMS:
#  flutter_sms:
#    git: https://github.com/Flutter-Tent/flutter_sms.git

  # Firebase:
  firebase_core: any
  cloud_firestore: any
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
